### ISSUE TITLE
Change "export to GeoTIFF" language?

### ISSUE THREAD

**Issue by itspangler** [allmaps/allmaps.github.io#5]
Right now, the home page says "Allmaps can export georeferenced maps to formats like GeoJSON or GeoTIFF." Should this be removed until there is a more intuitive way for users to "export to GeoTIFF" (e.g., a clickable button in Allmaps Viewer)? My understanding is that the only way to currently do this is a combination of the Allmaps API + CLI/GDAL—but maybe I'm missing something?

**Comment by cleorose** [comment]
from [ticket 762](https://github.com/orgs/geobtaa/projects/4/views/28?pane=issue&itemId=93332512&issue=geobtaa%7Cmetadata%7C762)) 
All records that are marked 'true' under 'georeferenced' are also necessarily marked 'true' under 'georeferenced with allmaps'

Recommendations:
on search results page:

Change "Georeferenced" facet to "Downloadable GeoTIFF"
Change "Georeferenced via Allmaps Plugin" facet to "Map Overlay"
Change logic for the plugin so that these two facets aren't connected
on resource/item viewer page:
change "Georeferenced Map" tab along the top to "Map Overlay"
change "Georeference" box in right sidebar and the link within that box. "Map Overlay" and "create georeferenced map overlay with Allmaps" or "view Allmaps georeferenced Map overlay"
